
import { S3Client, PutObjectCommand } from "@aws-sdk/client-s3";

// =================================================================================
// YOUR AWS S3 CREDENTIALS
// ⚠️ WARNING: In a production app, use pre-signed URLs generated by a backend.
// Defining secrets in frontend code (even via env vars) exposes them to the user.
// =================================================================================
const AWS_REGION = process.env.AWS_REGION || 'us-east-1';
const AWS_ACCESS_KEY_ID = process.env.AWS_ACCESS_KEY_ID || ''; 
const AWS_SECRET_ACCESS_KEY = process.env.AWS_SECRET_ACCESS_KEY || '';
const S3_BUCKET_NAME = process.env.S3_BUCKET_NAME || '';

// Initialize the S3 Client
const s3Client = new S3Client({
  region: AWS_REGION,
  credentials: {
    accessKeyId: AWS_ACCESS_KEY_ID,
    secretAccessKey: AWS_SECRET_ACCESS_KEY,
  },
});

export const uploadFileToS3 = async (file: File): Promise<{ url?: string; error?: string }> => {
  try {
    if (!AWS_ACCESS_KEY_ID || !AWS_SECRET_ACCESS_KEY) {
      return { error: "AWS credentials are missing in configuration." };
    }

    // 1. Generate a unique file name
    const fileExt = file.name.split('.').pop();
    const fileName = `${Date.now()}_${Math.random().toString(36).substring(7)}.${fileExt}`;
    const key = `profiles/${fileName}`; // Folder path in bucket

    // 2. Create the Upload Command
    const command = new PutObjectCommand({
      Bucket: S3_BUCKET_NAME,
      Key: key,
      Body: file,
      ContentType: file.type,
      // Note: ACLs are often disabled by default in new buckets. 
      // Ensure your bucket policy allows public read if you want to access the URL directly,
      // OR use CloudFront / Presigned URLs for access.
      // ACL: 'public-read', 
    });

    // 3. Send the command to S3
    await s3Client.send(command);

    // 4. Construct the Public URL
    // This assumes the bucket object is publicly readable.
    const url = `https://${S3_BUCKET_NAME}.s3.${AWS_REGION}.amazonaws.com/${key}`;

    return { url };

  } catch (error: any) {
    console.error("S3 Upload Error:", error);
    return { error: error.message || "Failed to upload to Amazon S3" };
  }
};
